spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d6j8tj94tr6s739akkf0-a.frankfurt-postgres.render.com/veebipood_01_26
spring.datasource.username=veebipood_user
spring.datasource.password=VZLq5zoSuuAryOTfXa5GKUgj43u87IFi

logging.file.name=logs.log

everypay.username=e36eb40f5ec87fa2
everypay.password=7b91a3b9e1b74524c2e9fc282f8ac8cd
#https://pay.every-pay.eu/api/v4
everypay.base-url=https://igw-demo.every-pay.com/api/v4
everypay.customer-url=https://www.err.ee
jwt.secret-key=KpDUDJpuIjyJqtQQ9755v8eWaPh1pcWFE1rIguxrZvE

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=85a9dd5c2e103d
spring.mail.password=7a132f6f0c27ef
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#frontend.url=https://back-end-01-2026-frontend.onrender.com
frontend.url=http://localhost:5173

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis