spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/shop
spring.datasource.username=postgres
spring.datasource.password=root

logging.file.name=logs.log

everypay.username=e36eb40f5ec87fa2
everypay.password=7b91a3b9e1b74524c2e9fc282f8ac8cd
#https://pay.every-pay.eu/api/v4
everypay.base-url=https://igw-demo.every-pay.com/api/v4
everypay.customer-url=https://www.err.ee
jwt.secret-key=KpDUDJpuIjyJqtQQ9755v8eWaPh1pcWFE1rIguxrZvE
